feat : git action 자동 배포 설정 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -77,3 +77,48 @@ jobs:
           context: .
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/pickmeal:latest
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: SSH key 설정
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
+          chmod 600 ~/.ssh/ec2_key.pem
+
+      - name: EC2 등록
+        run: |
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name: EC2 배포
+        run: |
+          ssh -i ~/.ssh/ec2_key.pem \
+          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
+          
+          cd ~/pickmeal
+          
+          docker compose -f compose.prod.yml pull app
+          
+          docker compose -f compose.prod.yml up -d --force-recreate app
+          
+          docker compose -f compose.prod.yml ps
+          
+          sleep 20
+          
+          for i in {1..10}; do
+          if curl --fail --silent http://localhost:8080/actuator/health > /dev/null; then
+          echo "Application is healthy"
+          exit 0
+          fi
+        
+          echo "Waiting for application..."
+          sleep 5
+          done
+          
+          echo "Application health check failed"
+          exit 1
+          
+          EOF
